### ISSUE TITLE
hi, i am japanese

### ISSUE THREAD

**Issue by SauerkrautFFish** [xmmmmmovo/MineShader#1]
hi, how r u, my name is ma, can you tell me how to use this tool to do mine shader?

**Comment by xmmmmmovo** [comment]
You need to buy the Minecraft and apply this shader

**Comment by SauerkrautFFish** [comment]
do you know age of empire 2? do you like it?

**Comment by xmmmmmovo** [comment]
No, I think this game is a piece of ♥♥♥♥.

**Comment by xmmmmmovo** [comment]
And I think the game, *Stronghold: Definitive Edition* is more suitable for you.

**Comment by SauerkrautFFish** [comment]
thank you, and i want to tell you, bytedance has some new position now, it is time for you to get one.

**Comment by SauerkrautFFish** [comment]
whats more, i am writing the code for blind date record system. you are welcome to try it when the time comes.

**Comment by xmmmmmovo** [comment]
OKOK, I will.
